[project]
name = "taskclf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fruitiecutiepie", email = "104437268+fruitiecutiepie@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
taskclf = "taskclf:main"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"
